const fs = require('node:fs');
const assert = require('node:assert/strict');
const {JSDOM} = require('jsdom');
(async()=>{
const dom = new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://example.org',runScripts:'outside-only'});
const w=dom.window;
const src=fs.readFileSync('app.js','utf8');
const section=src.slice(src.indexOf('function initFormLogic()'),src.indexOf('// --- Social Insurance Calculator Modal ---'));
w.eval('const state={isDemoMode:false,gasUrl:"https://example.org/api",expenseCategories:[]}; function showLoading(){} function showToast(){} function syncWithGas(){} '+section+';initFormLogic();');
const d=w.document;
d.getElementById('form-select-asset').click();
assert.equal(d.getElementById('asset-form').classList.contains('hidden'),false);
assert.equal(d.getElementById('income-form').classList.contains('hidden'),true);
d.getElementById('asset-date').value='2026-09-15';
d.getElementById('asset-zaikei').value='45000';
d.getElementById('asset-shares').value='1.575';
d.getElementById('inc-gross').value='300000';
let payload;
w.fetch=async(url,options)=>{payload=JSON.parse(options.body);return {ok:true,json:async()=>({status:'success'})};};
d.getElementById('asset-form').dispatchEvent(new w.Event('submit',{cancelable:true}));
await new Promise(r=>setTimeout(r,10));
assert.deepEqual(payload,{type:'asset',date:'2026-09-15',zaikei:45000,shares:1.575});
assert.equal(d.getElementById('asset-date').value,'2026-09-15');
assert.equal(d.getElementById('asset-zaikei').value,'');
assert.equal(d.getElementById('inc-gross').value,'300000');
assert.equal(d.getElementById('asset-form').classList.contains('hidden'),false);
d.getElementById('asset-zaikei').value='90000';d.getElementById('asset-shares').value='2';
w.fetch=async()=>{throw new Error('offline');};
d.getElementById('asset-form').dispatchEvent(new w.Event('submit',{cancelable:true}));
await new Promise(r=>setTimeout(r,10));
assert.equal(d.getElementById('asset-zaikei').value,'90000');
d.getElementById('form-select-expense').click();
assert.equal(d.getElementById('asset-form').classList.contains('hidden'),true);
console.log('Asset form payload, tab switching, retained date, isolated reset, failed-save retention: passed');
})();
